### ISSUE TITLE
The demo throws an exception of "Uncaught [ModJS] Cannot find module `fbjs/lib/ExecutionEnvironment`"

### ISSUE THREAD

**Issue by luozt** [qqiangwu/fis3-hook-npm#2]
I run build `npm run build` and `cd .dev && http-server -a 127.0.0.1 -p 8001`. Then open `http://127.0.0.1:8001/` but the console threw an error: "Uncaught [ModJS] Cannot find module `fbjs/lib/ExecutionEnvironment`"

**Comment by qqiangwu** [comment]
So, what's your npm version? The hook currently only works with 3.x. Or you
can check your generated map.json to see if `fbjs/lib/ExecutionEnvironment`
exists.

Also note that fis3 team officially has fis3-hook-node_modules.

**Comment by luozt** [comment]
I had just installed the latest nodejs with engines of `"node": ">=5.3.0","npm": ">=3.5.3"` and then checked the map.json which contained `"fbjs/lib/warning","fbjs/lib/ExecutionEnvironment"`. However, the error still existed.

But one thing I had mistaken is the project I ran was [qqiangwu/site](https://github.com/qqiangwu/site). It is not from the demo...

**Comment by qqiangwu** [comment]
Maybe you can delete old node_modules since they are installed by npm2.x
and rerun `npm install` and `fis3 release -cd .dev`

**Comment by luozt** [comment]
Eh, reinstall npm modules made some differences even though there were still some errors. And, since it was not the bug of this project, close it.

**Comment by qqiangwu** [comment]
Sorry to waste your time. When I develop this project, official hook
fis3-hook-node_modules is not released yet. Currently I'm use this project
in my organization's internal project and it works well. If you decided to
use fis3 + npm as your tool, LEARNING FIS3 FIRST!
